# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/FPGA_Contest_Proj/Con_proj_led/Con_proj_led.srcs/sources_1/ip/CLK_400MHZ/CLK_400MHZ.xci
# IP: The module: 'CLK_400MHZ' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA_Contest_Proj/Con_proj_led/Con_proj_led.srcs/sources_1/ip/CLK_400MHZ/CLK_400MHZ_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_400MHZ'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FPGA_Contest_Proj/Con_proj_led/Con_proj_led.srcs/sources_1/ip/CLK_400MHZ/CLK_400MHZ.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_400MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FPGA_Contest_Proj/Con_proj_led/Con_proj_led.srcs/sources_1/ip/CLK_400MHZ/CLK_400MHZ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_400MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/FPGA_Contest_Proj/Con_proj_led/Con_proj_led.srcs/sources_1/ip/CLK_400MHZ/CLK_400MHZ.xci
# IP: The module: 'CLK_400MHZ' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA_Contest_Proj/Con_proj_led/Con_proj_led.srcs/sources_1/ip/CLK_400MHZ/CLK_400MHZ_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_400MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FPGA_Contest_Proj/Con_proj_led/Con_proj_led.srcs/sources_1/ip/CLK_400MHZ/CLK_400MHZ.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_400MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FPGA_Contest_Proj/Con_proj_led/Con_proj_led.srcs/sources_1/ip/CLK_400MHZ/CLK_400MHZ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_400MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
